"""initial schema

Revision ID: 0e99f1ed859b
Revises: 
Create Date: 2026-06-22 03:15:48.723238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e99f1ed859b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('report_id')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('report_type')

    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("'Nueva'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'Nueva'"))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type', sa.TEXT(), server_default=sa.text("'Reporte'"), nullable=False))
        batch_op.add_column(sa.Column('assigned_to_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['assigned_to_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'report', ['report_id'], ['id'])

    # ### end Alembic commands ###
